name: Deploy fake

on:
    workflow_call:
        secrets:
            ambiente:
                required: true
                description: "Ambiente onde vai ser feito o deploy"
jobs:
    deploy-kubernetes:  
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.AMBIENTE_PARAMETRO }}"
            - name: CURL Deploy no ambiente
              run: "curl -X POST https://webhook.site/19996667-edcb-462c-92f2-a90d449cfd7b -d '{ ambiente: ${{ secrets.AMBIENTE_PARAMETRO }}'}"