name: Deploy fake

on:
    workflow_call:
jobs:
    deploy-kubernetes:  
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.AMBIENTE_PARAMETRO }}"
            - name: CURL Deploy no ambiente
              run: "curl -X POST https://webhook.site/19996667-edcb-462c-92f2-a90d449cfd7b -d '{ ambiente: ${{ secrets.AMBIENTE_PARAMETRO }}'}"